site_name: B站录播姬
site_url: !ENV [SITE_URL, "https://rec.danmuji.org/"]
site_description: B站录播姬是一个方便好用免费开源的B站直播录制工具
site_author: genteure

strict: !ENV [CI, false]

repo_url: https://github.com/BililiveRecorder/BililiveRecorder
repo_name: BililiveRecorder/BililiveRecorder

edit_uri: https://github.com/BililiveRecorder/website/blob/main/docs/

copyright: "Copyright &copy; 2022 Genteure. 文档内容为 CC-BY-NC-SA 授权"

watch:
  - data
  - include
  - overrides

theme:
  name: material
  custom_dir: overrides
  language: zh
  favicon: favicon.png
  logo: favicon.svg
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/weather-night
        name: 切换到亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换到暗色模式

nav:
  - 首页: index.md
  - 用户文档:
      - user/index.md
      - 软硬件要求: user/system-requirements.md
      - 安装使用: user/install.md
      - 常见问题: user/faq.md
      - 更新历史: user/change-log.md
      - 弹幕录制: user/danmaku.md
      - 软件设置:
          - 设置项: user/settings.md
          - 录制模式: user/record-mode.md
          - 文件名格式: user/file-name-template.md
          - 配置文件格式: user/config-file.md
          - 用户脚本: user/user-script.md
      - 工具箱:
          - user/toolbox/index.md
          - 录播修复: user/toolbox/repair.md
          - 转封装: user/toolbox/remux.md
          - 弹幕合并: user/toolbox/danmaku-merge.md
      - 录播修复说明: user/repair.md
      - 修复问题反馈: user/repair-feedback.md
      - 命令行参数: user/commands.md
      - Webhook: user/webhook.md
      - 其他工具和项目: user/other-projects.md
  - 开发文档:
      - dev/index.md
      - 项目结构: dev/projects.md
      - 翻译录播姬: dev/translations.md
      - 录播修复系统: dev/repair.md
      - 直播 CDN 信息: dev/bilibili-cdn.md

plugins:
  - search
  - tags
  - macros:
      on_error_fail: !ENV [CI, false]
      include_dir: include
      include_yaml:
        - dns_data_bcdn: data/dns_data_bcdn.json
        - dns_data_gotcha: data/dns_data_gotcha.json
        - brec_settings: data/brec_settings.json
  - brec-redirects:
      build_cloudflare_pages_redirects: true
      build_redirects_json: true
      write_both_url_type: true
      redirect_maps:
        # Links
        "link/faq.md": "user/faq.md"
        "link/fix_feedback.md": "user/repair-feedback.md"
        "link/sponsor.md": "https://afdian.net/@genteure"
        "link/translate.md": "https://crowdin.com/project/bililiverecorder"
        # Old jekyll website
        docs.md: user/index.md
        docs/translate.md: dev/translations.md
        docs/toolbox.md: user/toolbox/index.md
        docs/toolbox/danmaku_merge.md: user/toolbox/danmaku-merge.md
        docs/toolbox/fix.md: user/toolbox/repair.md
        docs/process.md: user/repair.md
        docs/process/feedback.md: user/repair-feedback.md
        docs/faq.md: user/faq.md
        docs/cli.md: user/commands.md
        docs/cli/docker.md: user/commands.md
        docs/cli/config_file.md: user/config-file.md
        docs/basic/webhook.md: user/webhook.md
        docs/basic/settings.md: user/settings.md
        docs/basic/related.md: user/other-projects.md
        docs/basic/record_mode.md: user/record-mode.md
        docs/basic/danmaku.md: user/danmaku.md
        docs/basic/auto_cut.md: user/index.md # 没有对应的页面
        docs/desktop/flvprocess.md: user/repair.md
        docs/desktop/danmaku.md: user/danmaku.md
        docs/storage.md: user/index.md
        docs/server.md: user/index.md
        docs/home.md: user/index.md
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      js_files:
        - assets/javascripts/homepage.js
        - assets/javascripts/brec-version.js
      css_files:
        - assets/stylesheets/homepage.css
        - assets/stylesheets/brec-version.css

extra_javascript:
  - assets/javascripts/brec-version.min.js

extra_css:
  - assets/stylesheets/brec-version.min.css

extra:
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/7033853
      name: 哔哩哔哩 @genteure
    - icon: "afdian/afd logo-发电紫"
      link: https://afdian.net/@genteure
      name: 爱发电 @genteure
    - icon: octicons/mark-github-16
      link: https://github.com/BililiveRecorder
      name: GitHub 组织 @BiliveRecorder
    - icon: fontawesome/brands/qq
      link: https://jq.qq.com/?_wv=1027&k=5NPC2dt
      name: 反馈QQ群 689636812
    - icon: material/email-edit
      link: mailto:rec@danmuji.org
      name: 反馈邮箱 rec@danmuji.org
  analytics:
    provider: google
    property: G-NH133VH2RG

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
