name: publish

on:
  push:
    branches:
      - master 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material mkdocs-minify-plugin mkdocs-redirects mkdocs-macros-plugin
          pip install -e plugins/mkdocs-redirects/
      - run: mkdocs gh-deploy --force
